name: daejeon
description: Simple BLoC-based MVI package for Flutter.
version: 0.0.1
homepage: https://github.com/Apeiro-Corp/flutter-daejeon
repository: https://github.com/Apeiro-Corp/flutter-daejeon
documentation: https://github.com/Apeiro-Corp/flutter-daejeon

topics:
  - bloc
  - state-management
  - mvi
  - side-effect

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
